### ISSUE TITLE
Could not import time module

### ISSUE THREAD

**Issue by zzdever** [pybee/Python-iOS-support#21]
I continuously encounter an error: "ImportError: No module named 'time' " .
As time module is depended by several other modules, it becomes impossible to me to continue.

It seems time module is not correctly linked in the building phase as make shows:

Undefined symbols for architecture armv7:
  "_PyArg_ParseTuple", referenced from:
      _time_sleep in timemodule.o
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_ctime in timemodule.o
      _time_strftime in timemodule.o
      _time_get_clock_info in timemodule.o
      _gettmarg in timemodule.o
      ...
  "_PyArg_UnpackTuple", referenced from:
      _time_asctime in timemodule.o
  "_PyBool_FromLong", referenced from:
      _time_get_clock_info in timemodule.o
  "_PyDict_New", referenced from:
      _time_get_clock_info in timemodule.o
  "_PyDict_SetItemString", referenced from:
      _time_get_clock_info in timemodule.o
  "_PyErr_CheckSignals", referenced from:
      _time_sleep in timemodule.o
  "_PyErr_Clear", referenced from:
      _time_perf_counter in timemodule.o
      _time_get_clock_info in timemodule.o
  "_PyErr_NoMemory", referenced from:
      _time_strftime in timemodule.o
  "_PyErr_Occurred", referenced from:
      _tmtotuple in timemodule.o
      _gettmarg in timemodule.o
  "_PyErr_SetFromErrno", referenced from:
      _time_sleep in timemodule.o
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_asctime in timemodule.o
      _time_ctime in timemodule.o
      _time_strftime in timemodule.o
  "_PyErr_SetString", referenced from:
      _time_clock in timemodule.o
      _time_sleep in timemodule.o
      _time_mktime in timemodule.o
      _time_get_clock_info in timemodule.o
      _gettmarg in timemodule.o
      _checktm in timemodule.o
      _py_process_time in timemodule.o
      ...
  "_PyEval_RestoreThread", referenced from:
      _time_sleep in timemodule.o
  "_PyEval_SaveThread", referenced from:
      _time_sleep in timemodule.o
  "_PyExc_IOError", referenced from:
      _time_sleep in timemodule.o
  "_PyExc_OSError", referenced from:
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_asctime in timemodule.o
      _time_ctime in timemodule.o
      _time_strftime in timemodule.o
  "_PyExc_OverflowError", referenced from:
      _time_mktime in timemodule.o
  "_PyExc_RuntimeError", referenced from:
      _time_clock in timemodule.o
      _time_get_clock_info in timemodule.o
      _py_process_time in timemodule.o
  "_PyExc_TypeError", referenced from:
      _gettmarg in timemodule.o
  "_PyExc_ValueError", referenced from:
      _time_sleep in timemodule.o
      _time_get_clock_info in timemodule.o
      _checktm in timemodule.o
  "_PyFloat_FromDouble", referenced from:
      _time_time in timemodule.o
      _time_clock in timemodule.o
      _time_mktime in timemodule.o
      _time_monotonic in timemodule.o
      _time_perf_counter in timemodule.o
      _time_get_clock_info in timemodule.o
      _py_process_time in timemodule.o
      ...
  "_PyImport_ImportModuleNoBlock", referenced from:
      _time_strptime in timemodule.o
  "_PyLong_AsLong", referenced from:
      _gettmarg in timemodule.o
  "_PyLong_FromLong", referenced from:
      _tmtotuple in timemodule.o
  "_PyMem_Free", referenced from:
      _time_strftime in timemodule.o
  "_PyMem_Malloc", referenced from:
      _time_strftime in timemodule.o
  "_PyModule_AddIntConstant", referenced from:
      _PyInit_time in timemodule.o
  "_PyModule_AddObject", referenced from:
      _PyInit_time in timemodule.o
  "_PyModule_Create2", referenced from:
      _PyInit_time in timemodule.o
  "_PyStructSequence_InitType2", referenced from:
      _PyInit_time in timemodule.o
  "_PyStructSequence_New", referenced from:
      _tmtotuple in timemodule.o
  "_PyUnicode_AsUTF8", referenced from:
      _gettmarg in timemodule.o
  "_PyUnicode_AsWideCharString", referenced from:
      _time_strftime in timemodule.o
  "_PyUnicode_DecodeLocale", referenced from:
      _tmtotuple in timemodule.o
  "_PyUnicode_FromFormat", referenced from:
      _time_asctime in timemodule.o
      _time_ctime in timemodule.o
  "_PyUnicode_FromString", referenced from:
      _time_get_clock_info in timemodule.o
  "_PyUnicode_FromWideChar", referenced from:
      _time_strftime in timemodule.o
  "_Py_BuildValue", referenced from:
      _PyInit_time in timemodule.o
  "__PyNamespace_New", referenced from:
      _time_get_clock_info in timemodule.o
  "__PyObject_CallMethodId", referenced from:
      _time_strptime in timemodule.o
  "__PyTime_ObjectToTime_t", referenced from:
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_ctime in timemodule.o
  "__PyTime_gettimeofday_info", referenced from:
      _time_time in timemodule.o
      _time_perf_counter in timemodule.o
      _time_get_clock_info in timemodule.o
  "__Py_NoneStruct", referenced from:
      _time_sleep in timemodule.o
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_ctime in timemodule.o
      _gettmarg in timemodule.o
  "___error", referenced from:
      _time_sleep in timemodule.o
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_asctime in timemodule.o
      _time_ctime in timemodule.o
      _time_strftime in timemodule.o
  "___floatundidf", referenced from:
      _time_monotonic in timemodule.o
      _time_perf_counter in timemodule.o
      _time_get_clock_info in timemodule.o
  "___stack_chk_fail", referenced from:
      _PyInit_time in timemodule.o
  "___stack_chk_guard", referenced from:
      _PyInit_time in timemodule.o
  "_clock", referenced from:
      _time_clock in timemodule.o
      _time_get_clock_info in timemodule.o
      _py_process_time in timemodule.o
  "_floor", referenced from:
      _time_sleep in timemodule.o
  "_fmod", referenced from:
      _time_sleep in timemodule.o
  "_getrusage", referenced from:
      _py_process_time in timemodule.o
  "_gmtime", referenced from:
      _time_gmtime in timemodule.o
  "_localtime", referenced from:
      _PyInit_time in timemodule.o
      _time_localtime in timemodule.o
      _time_asctime in timemodule.o
      _time_ctime in timemodule.o
      _time_strftime in timemodule.o
  "_mach_absolute_time", referenced from:
      _time_monotonic in timemodule.o
      _time_perf_counter in timemodule.o
      _time_get_clock_info in timemodule.o
  "_mach_timebase_info", referenced from:
      _time_monotonic in timemodule.o
      _time_perf_counter in timemodule.o
      _time_get_clock_info in timemodule.o
  "_mktime", referenced from:
      _time_mktime in timemodule.o
  "_select$DARWIN_EXTSN", referenced from:
      _time_sleep in timemodule.o
  "_strcmp", referenced from:
      _time_get_clock_info in timemodule.o
  "_strncpy", referenced from:
      _PyInit_time in timemodule.o
  "_sysconf", referenced from:
      _py_process_time in timemodule.o
  "_time", referenced from:
      _PyInit_time in timemodule.o
      _time_gmtime in timemodule.o
      _time_localtime in timemodule.o
      _time_asctime in timemodule.o
      _time_ctime in timemodule.o
      _time_strftime in timemodule.o
     (maybe you meant: _PyInit_time)
  "_times", referenced from:
      _py_process_time in timemodule.o
  "_wcsftime", referenced from:
      _time_strftime in timemodule.o
  "_wcslen", referenced from:
      _time_strftime in timemodule.o
  "start", referenced from:
     implicit entry/start for main executable

**Comment by freakboy3742** [comment]
I've just tried the following program:
```
import time

print("START SLEEPING")
time.sleep(10)
print("STOP SLEEPING")
```

which worked exactly as you'd expect. Based on the stack trace, I'm guessing the framework hasn't been added fully to the project. It isn't as simple as just dropping the framework into your project; there are a few other pieces that need to be set up. That's why there's a [Python-iOS-template](https://github.com/pybee/Python-iOS-template) project, and support for iOS in [briefcase](https://github.com/pybee/briefcase).

I'm guessing the actionable item here is to document what else needs to be done in order to add Python-iOS-template to your project. You can check the template project for exact details, it's the following two steps:
* Add Python.framework to the "Linked Projects and Frameworks" section under the "General" configuration for the project.
* Add a build phase to the project, after "Target dependencies", but before "Compile Sources"; this build phase should be a shell script, with the following content:
```
mkdir -p "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Python.framework/Resources"
mkdir -p "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Application Support/org.example.todolist"
rsync -pvtrL --exclude .hg --exclude .svn --exclude .git "$PROJECT_DIR/Python.framework/Resources/lib" "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Python.framework/Resources"
rsync -pvtrL --exclude .hg --exclude .svn --exclude .git "$PROJECT_DIR/Python.framework/Resources/include" "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Python.framework/Resources"
rsync -pvtrL --exclude .hg --exclude .svn --exclude .git "$PROJECT_DIR/app" "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Application Support/org.example.todolist"
mkdir -p "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Python.framework/Resources/lib/python`readlink $PROJECT_DIR/Python.framework/Versions/Current`/site-packages/"
rsync -pvtrL --exclude .hg --exclude .svn --exclude .git "$PROJECT_DIR/app_packages/" "$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Library/Python.framework/Resources/lib/python`readlink $PROJECT_DIR/Python.framework/Versions/Current`/site-packages/"
```

**Comment by zzdever** [comment]
Oh, it seems I linked to wrong libbz2 and liblzma. 
Before this issue I encountered linking error, so I manually add libbz2 and liblzma. To solve the time module issue, I installed xz to the system. And a newly create Xcode project does not see linking error. **And, surprisingly, the time module works!!**

Thank you so much.
