### ISSUE TITLE
Missing references to BZ2 and LZMA libraries

### ISSUE THREAD

**Issue by stsievert** [pybee/Python-iOS-support#24]
After adding Python.framework and OpenSSL.framework, there are missing references to functions in the BZ2 and LZMA frameworks.

<img width="262" alt="screen shot 2016-06-03 at 9 42 59 am" src="https://cloud.githubusercontent.com/assets/1320475/15786096/9858b84e-296f-11e6-9126-0fccb5a99346.png">

This issue can be fixed by locating `Python-iOS-support/build/iOS/{xz, bzip2}/lib/lib{lzma, bz2}.a` and adding it to the Xcode project (which I did by dragging and dropping). This works, at least for the simulator.

**Comment by freakboy3742** [comment]
This has been resolved in the new Python-Apple-support package, which merges iOS, tvOS and macOS support into a single package.
